version: '2'

services:
  testlink_web:
    #image: techknowlogick/testlink:web
    build: ./build/testlink_web
    restart: unless-stopped
    volumes_from:
      - testlink_app
    depends_on:
      - testlink_php
    ports:
      - 80:80
    environment:
      - DATABASE_HOST=testlink_db
      - DATABASE_PASS=testlink_x
    container_name: testlink_web
  testlink_php:
    #image: techknowlogick/testlink:php
    build: ./build/testlink_php
    volumes_from:
      - testlink_app
#      - testlink_data
    depends_on:
      - testlink_db
    container_name: testlink_php
  testlink_db:
    image: mariadb:10
    restart: unless-stopped
    environment:
     - MYSQL_DATABASE=testlink
     - MYSQL_ROOT_PASSWORD=testlink_x
    container_name: testlink_db
  testlink_app:
    #image: techknowlogick/testlink:latest
    build: ./build/testlink_app
    container_name: testlink_app
    volumes: 
#     - ./data/testlink:/var/testlink
     - ./data/testlink/upload_area:/var/testlink/upload_area 
     - ./data/testlink/logs:/var/testlink/logs
#  testlink_data:
#    #image: techknowlogick/testlink:data
#    build: ./build/testlink_data
#    container_name: testlink_data
